name: Build

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build:
    name: Build
    runs-on: windows-2022
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.2.0
        with:
          fetch-depth: 1
          submodules: 'true'

      - name: Configure CMake (MSVC)
        run: |
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=MinSizeRel
        shell: cmd

      - name: Build all
        run: |
          cmake --build ${{github.workspace}}/build --config MinSizeRel
        shell: cmd

      - name: Upload KobeBryant.exe
        uses: actions/upload-artifact@v3.1.0
        with:
          name: KobeBryant.exe
          path: |
            ${{github.workspace}}\output\bin\KobeBryant.exe

      - name: Upload SDK
        uses: actions/upload-artifact@v3.1.0
        with:
          name: SDK
          path: |
            ${{github.workspace}}\output\sdk

      - name: Update SDK
        if: github.event_name == 'push'
        working-directory: ${{github.workspace}}
        run: |
          mkdir ~/.ssh
          touch ~/.ssh/known_hosts
          ssh-keygen -R github.com
          curl -L https://api.github.com/meta | jq -r '.ssh_keys | .[]' | sed -e 's/^/github.com /' >> ~/.ssh/known_hosts
          echo "-----BEGIN OPENSSH PRIVATE KEY-----" >> ~/.ssh/id_rsa
          echo ${{secrets.DEPLOY_KEY}} >> ~/.ssh/id_rsa
          echo "-----END OPENSSH PRIVATE KEY-----" >> ~/.ssh/id_rsa
          git config --global user.name "github-actions[bot]"
          git config --global user.email "186297309+github-actions[bot]@users.noreply.github.com"
          cd scripts
          cmd //c "UpdateSDK.cmd action"
        shell: bash
